spring:
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/beauty_salon_booking
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none