spring:
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 271176
  jpa:
    hibernate:
      ddl-auto: none